version: "2"
services:
  cleandev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8000:8000"
     - "8080:8080"
     - "9876:9876"
     - "9222:9222"
    volumes:
     - ".:/vagrant"
    environment:
     - PYTHONDONTWRITEBYTECODE=true
     - NODE_PATH=/vagrant-dev/node_modules/
     - GGRC_DATABASE_URI=mysql+mysqldb://root:root@db/ggrcdev?charset=utf8
     - GGRC_DATABASE_HOST=db
     - OAUTHLIB_INSECURE_TRANSPORT=1
    links:
     - db
  db:
    image: mysql:5.6
    ports:
     - "3306:3306"
    volumes:
     - "./provision/docker/mysql:/etc/mysql/conf.d"
    environment:
     - MYSQL_ROOT_PASSWORD=root
